services:
  app:
    build:
      context: ./php
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - mysql

  nginx:
    image: nginx:1.25
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  redis:
    image: redis:7
    container_name: laravel-redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: middle_php_dev
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    #ports:
      #- "3306:3306"  #проброс наружу (например, для DBeaver). Можно убрать, если не нужен

volumes:
  mysql_data: